slogan: "在路上"

theme: cosmo
inverse: false

menu:
  - title: Archives
    url: archives
    intro: "All the articles."
    icon: "fa fa-archive"
  - title: Categories
    url: categories
    intro: "All the categories."
    icon: "fa fa-folder"
  - title: Tags
    url: tags
    intro: "All the tags."
    icon: "fa fa-tags"
  - title: About
    url: about
    intro: "About me."
    icon: "fa fa-user"

links:
  - title: "My Github"
    url: http://www.github.com/ccsheller
    intro: "My Github account."
    icon: "fa fa-github"

widgets:
- category
- tagcloud
- recent_posts
- links
- recent_comments

rss:
fancybox: true
favicon: favicon.png
duoshuo_shortname: #freemindtheme

# Recommended posts
# Dependency: https://github.com/huiwang/hexo-recommended-posts
recommended_posts:
  enabled: true

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
bdshare: true
jiathis: false

# built-in comment system
comment_js:
  type: "github"
  user: "ccsheller"
  repo: "ccsheller.github.io"
  client_id: 
  client_secret: 
  count: 5
